### ISSUE TITLE
Padding Oracle Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [twofas/encryption#3]
https://github.com/twofas/encryption/blob/0574c2843d4d3fb61a8e94ff78e710d7aa66a2cd/src/RsaCryptographer.php#L55

See also:

* http://archiv.infsec.ethz.ch/education/fs08/secsem/bleichenbacher98.pdf
* https://crypto.stackexchange.com/questions/12688/can-you-explain-bleichenbachers-cca-attack-on-pkcs1-v1-5
* https://framework.zend.com/security/advisory/ZF2015-10

Solution: Specify OAEP padding.

**Comment by SlimMike** [comment]
Thanks for the analysis and sharing your findings with us and the community. 

We confirm as you mentioned, that there is a vulnerability in the RSA encryption/decryption process. 

Fortunately, our users were not under the threat, as we send data through a PUSHER on a private channel, where is another encryption layer. 

As matters of security and integrity are important to us, I can advise that we are working on an update that will be published shortly.

Thank you for your intervention and feedback; we really do appreciate you making Magic Password more secure.
